server:
        name: one
        type: ssd_pm1733a
server:
        name: two
        type: ssd_pm1733a
server:
        name: three
        type: raid_1
        servers: 
          - one
          - two
generator:
        name: gen
        queue_depth: 1
        server: three
        # iops: 44850
        size: 65534
        percent_read: 100
simulation_time: 100000
