drives:
        name: ssd
        type: ssd_pm1733a
        instances: 24
raid:
        name: raid
        type: raid_dp
        stripe_width: 65536
        drives: 
          - ssd\d+
ioms:
        name: iom
        max_iops: 1000000
        mbps: 1000
        instances: 2
port:
        name: port1
        iom: iom1
        max_iops: 1000000
        mbps: 1000
port:
        name: port2
        iom: iom2
        max_iops: 1000000
        mbps: 1000
hba:
        name: hba1
        ports:
                - port1
hba:
        name: hba2
        ports:
                - port2
shelf:
        ioms:
          - iom\d+
        drives: 
          - ssd\d+
generator:
        name: gen1
        raid: raid
        # queue_depth: 2
        iops: 1000
        size: 65536
        percent_read: 0
        percent_random: 0
generator:
        name: gen2
        raid: raid
        # queue_depth: 2
        iops: 1000
        size: 65536
        percent_read: 0
        percent_random: 0
controller:
        name: controller1
        generators: 
          - gen1
        hbas:
          - hba1
controller:
        name: controller2
        generators: 
          - gen2
        hbas:
          - hba2
filer:
        name: filer1
        controllers: 
          - controller1
          - controller2
simulation_time: 1000000
