drive:
        name: ssd1
        type: ssd_pm1733a
drive:
        name: ssd2
        type: ssd_pm1733a
drive:
        name: ssd3
        type: ssd_pm1733a
drive:
        name: ssd4
        type: ssd_pm1733a
raid:
        name: raid
        type: raid_dp
        stripe_width: 512
        drives: 
          - ssd1
          - ssd2
          - ssd3
          - ssd4
shelf:
        drives: 
          - ssd1
          - ssd2
          - ssd3
          - ssd4
generator:
        name: gen1
        raid: raid
        queue_depth: 1
        # iops: 100
        size: 1024
        percent_read: 0
        percent_random: 0
simulation_time: 10000000
