server:
        name: ssd1
        type: ssd_pm1733a
server:
        name: ssd2
        type: ssd_pm1733a
server:
        name: ssd3
        type: ssd_pm1733a
server:
        name: ssd4
        type: ssd_pm1733a
server:
        name: raid
        type: raid_dp
        stripe_width: 512
        servers: 
          - ssd1
          - ssd2
          - ssd3
          - ssd4
generator:
        name: gen1
        queue_depth: 16
        server: raid
        # iops: 75900
        size: 1024
        percent_read: 0
        percent_random: 0
simulation_time: 100000
