drive:
        name: ssd1
        type: ssd_pm1733a
drive:
        name: ssd2
        type: ssd_pm1733a
drive:
        name: ssd3
        type: ssd_pm1733a
drive:
        name: ssd4
        type: ssd_pm1733a
raid:
        name: raid
        type: raid_dp
        stripe_width: 65536
        drives: 
          - ssd1
          - ssd2
          - ssd3
          - ssd4
iom:
        name: iom1
        max_iops: 1000000
iom:
        name: iom2
        max_iops: 1000000
hba:
        name: hba1
        iom: iom1
        max_iops: 1000000
        mbps: 1000
hba:
        name: hba2
        iom: iom2
        max_iops: 1000000
        mbps: 1000
shelf:
        ioms:
          - iom1
          - iom2
        drives: 
          - ssd1
          - ssd2
          - ssd3
          - ssd4
generator:
        name: gen1
        raid: raid
        queue_depth: 2
        # iops: 100
        size: 65536
        percent_read: 0
        percent_random: 0
generator:
        name: gen2
        raid: raid
        queue_depth: 2
        # iops: 100
        size: 65536
        percent_read: 0
        percent_random: 0
controller:
        name: controller1
        generators: 
          - gen1
        hbas:
          - hba1
controller:
        name: controller2
        generators: 
          - gen2
        hbas:
          - hba2
filer:
        name: filer1
        controllers: 
          - controller1
          - controller2
simulation_time: 1000000
